name: activity-classification
dependencies:
  - h5py=2.10.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pillow=7.0.0
  - plotly=4.5.2
  - python=3.7.6
  - pytorch=1.4.0
  - pywavelets=1.1.1
  - tensorboard=2.0.0
  - tqdm=4.42.1
