name: pigment-in-water
channels:
  - plotly
  - defaults
dependencies:
  - altair=3.2.0
  - keras=2.3.1
  - numpy=1.18.1
  - opencv=3.4.2
  - plotly=3.10.0
  - plotly-orca=1.3.1
  - psutil=5.6.3
  - python=3.7.7
  - scikit-learn=0.20.3
